<?php
/**
 * Implements hook_install().
 */
function unmanaged_user_pictures_main_install() {
  $spec = array(
      'type' => 'varchar',
      'length' => 256,
      'not null' => FALSE,
      'default' => '',
  );
  
  db_add_field('users', 'picture_unmanaged', $spec);
}

/**
 * Implements hook_uninstall().
 */
function unmanaged_user_pictures_main_uninstall(){
  db_drop_field('users', 'picture_unmanaged');
}

?>
